### ISSUE TITLE
Update Header and Footer on index.html

### ISSUE THREAD

**Issue by floydpink** [kollavarsham/calendar-vue#11]
Update `index.html` to bring in the header and footer from [the legacy calendar app](https://kollavarsham.org/calendar).

 * Match the navigation on the header to that of the legacy app
   * Exclude Language selection on top-right for now
 * Implement the `version` component on the bottom-left of the footer
   * tooltip/title
   * link destination
   * link text
 * Implement the LiCENSE component on the footer
   * link destination
   * link text

**Comment by carrotfarmer** [comment]
I'll work on the footer

**Comment by carrotfarmer** [comment]
Ok, I'm gonna have a go at the header
