### ISSUE TITLE
Add an under construction banner into index.html

### ISSUE THREAD

**Issue by floydpink** [kollavarsham/calendar-vue#12]
Replace the Vue.js boilerplate content with the attached image (aligned center and middle)

![under-construction](https://user-images.githubusercontent.com/171072/119857333-77b1eb80-bee1-11eb-8599-8a47850e13ad.png)

**Comment by carrotfarmer** [comment]
![image](https://user-images.githubusercontent.com/66675022/119940094-58cc5b80-bfac-11eb-8cbf-fb0417f5a2ee.png)
This is how it looks I have added the commits in #13.

**Comment by carrotfarmer** [comment]
Don't mind the purple color thats because of my screenshot tool

**Comment by carrotfarmer** [comment]
#14 fixes this.
