### ISSUE TITLE
e2e tests won't run

### ISSUE THREAD

**Issue by carrotfarmer** [kollavarsham/calendar-vue#32]
![](https://i.imgur.com/ZPQN73L.png)
```bash
npm run test:e2e
```
errors out with this error
```js

 ERROR  Failed to compile with 1 error                                  5:06:27 PM

 error  in css/index.06e0bbd3.css

Cannot use [chunkhash] or [contenthash] for chunk in 'js/[name].[contenthash:8].js' (use [hash] instead)

```
This looks to be an issue with Hot Module Replacement (I'm not sure tho), and it doesn't open up the interactive browser session. It doesn't look like it is detecting `tests/e2e/specs/test.js` either. Is this a problem?

**Comment by floydpink** [comment]
I’d seen it failing - didn’t add the issue to get back to it and fix

thanks for adding this - I will take a closer look into this

**Comment by carrotfarmer** [comment]
@floydpink Disabling hot module reloading fixes this. Can we use this as a temporary fix until we find the root cause of this issue?

**Comment by carrotfarmer** [comment]
```js
module.exports = {
  devServer: {
    host: "localhost",
    hot: false
  },
  pages: {
    index: {
      entry: "src/main.ts",
      template: "public/index.html",
      title: "Kollavarsham Calendar [BETA]"
    }
  },
  publicPath: process.env.NODE_ENV === "production" ? "/calendar-vue" : "/"
};
```

**Comment by floydpink** [comment]
That is a great find! Rather than disabling it, we can try to disable it for the e2e tests alone - I will push something shortly
