### ISSUE TITLE
Add first unit test

### ISSUE THREAD

**Issue by floydpink** [kollavarsham/calendar-vue#7]
* add a simple unit test following best practices for Vue.js
* select any popular unit-test framework for Vue.js
* ensure that tests can be run via `npm test` command

**Comment by carrotfarmer** [comment]
There is a built in testing library with comes with the package `vue`
Usage:
```vue
import {} from '@vue/test-utils'
```
[Docs](https://vuejs.org/v2/cookbook/unit-testing-vue-components.html)
